services:
  accounts:
    image: "felixl07/accounts:mini-bank"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mini-bank
  cards:
    image: "felixl07/cards:mini-bank"
    container_name: cards-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mini-bank
  loans:
    image: "felixl07/loans:mini-bank"
    container_name: loans-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mini-bank

networks:
  mini-bank:
    driver: "bridge"
