services:
  accountsdb:
    container_name: accountsdb-docker-compose
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb-docker-compose
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb-docker-compose
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  # rabbitmq must start properly before other service is started,
  # because all service is depending on rabbitmq
  rabbit-mq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 5s    # initial delay after container starts before health checks begin.
      retries: 10         # how many consecutive failures docker tolerates before marking the container as unhealthy
      interval: 10s       # docker will run the health check every 10 seconds.
      timeout: 5s         # if the health check takes longer than 5 seconds, it’s treated as a failure.
    extends:
      file: common-config.yml
      service: network-deploy-service

  # we must make sure that "configserver" is ready before running
  # accounts, cards and loans microservices.
  configserver:
    image: "felixl07/configserver:mini-bank"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit-mq:
        condition: service_healthy
    healthcheck:
      # --fail
      #   Tells curl to fail silently on server errors (like HTTP 500, 404).
      #   It won’t output the HTML error page — it just returns a non-zero exit code.
      # --silent
      #   Suppresses all the progress/output text.
      #   Makes the command quiet — you’ll only see the response body (if any).
      # grep UP
      #   If UP is found, the command succeeds (exit code 0).
      #   If UP is not found, it fails (exit code 1).
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s   # initial delay after container starts before health checks begin.
      retries: 10         # how many consecutive failures docker tolerates before marking the container as unhealthy
      interval: 10s       # docker will run the health check every 10 seconds.
      timeout: 5s         # if the health check takes longer than 5 seconds, it’s treated as a failure.
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "felixl07/eurekaserver:mini-bank"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      # --fail
      #   Tells curl to fail silently on server errors (like HTTP 500, 404).
      #   It won’t output the HTML error page — it just returns a non-zero exit code.
      # --silent
      #   Suppresses all the progress/output text.
      #   Makes the command quiet — you’ll only see the response body (if any).
      # grep UP
      #   If UP is found, the command succeeds (exit code 0).
      #   If UP is not found, it fails (exit code 1).
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s   # initial delay after container starts before health checks begin.
      retries: 10         # how many consecutive failures docker tolerates before marking the container as unhealthy
      interval: 10s       # docker will run the health check every 10 seconds.
      timeout: 5s         # if the health check takes longer than 5 seconds, it’s treated as a failure.
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "felixl07/accounts:mini-bank"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      # we're accessing this url in outside network so we're using the internal docker port
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    # accounts service will start only when configserver's and accountsdb's service condition is health
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config


  cards:
    image: "felixl07/cards:mini-bank"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      # we're accessing this url in outside network so we're using the internal docker port
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    # cards service will start only when configserver's service condition is health
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config


  loans:
    image: "felixl07/loans:mini-bank"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      # we're accessing this url in outside network so we're using the internal docker port
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    # loans service will start only when configserver's service condition is health
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  gatewayserver:
    image: "felixl07/gatewayserver:mini-bank"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

networks:
  mini-bank:
    driver: "bridge"
