services:
  network-deploy-service:
    networks:
      - mini-bank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      # tell docker to ping the host
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 10s    # initial delay after container starts before health checks begin.
      timeout: 10s         # if the health check takes longer than 5 seconds, it’s treated as a failure.
      interval: 10s       # docker will run the health check every 10 seconds.
      retries: 10         # how many consecutive failures docker tolerates before marking the container as unhealthy
    environment:
      MYSQL_ROOT_PASSWORD: root

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit-mq"
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.11.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-eurekaserver-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
