spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/philix07/bank-microservices-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  #      native:
  #        search-locations: "file:///D://Coding//Spring//Udemy - Microservices//config" #read configuration from the local file system
  #        search-locations: "classpath:/config" # read configuration from the classpath
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071


